### PR TITLE
Fix native linux support without wine

### LINKED ISSUE #12: Can't start emulator on Linux without wine
Hello,

Thank you for this pluggin. I was a bit desperate to be obliged to use eclipse.

Everything went just fine, setting was easy, build OK but fails with the following insult: 

Error running 'test': Cannot run program "wine" (in directory "/opt/sdk/connectiq-sdk/bin"): error=2, No such file or directory

I am surprised to read wine here.
Any suggestion?

Bertrand

### PR DESCRIPTION
**Pull request by snaggen**
This pull request removes the wine dependency for linux. I also created an abstract sdk helper class, and then one for each os to keep all the os specific things in one place. It felt cleaner than having it in the rest of the code. Also, I only use Linux, so my changes is not tested with anything else, but I tried to keep the commands for windows and mac... so it SHOULD work... which most probably might indicate that it have a chance of working.... 
Anyway, on Linux I'm able to use the run button to test my watchface in a simulator with no wine installed. 

However, the Garmin Linux SDK is using VERY old deps
so, to get that to work you might need to find and setup
the dependencies manually. For Fedora 27/28 I setup the following libs:
libjavascriptcoregtk-1.0.so -> libjavascriptcoregtk-1.0.so.0.16.19
libjavascriptcoregtk-1.0.so.0 -> libjavascriptcoregtk-1.0.so.0.16.19
libjavascriptcoregtk-1.0.so.0.16.19
libjpeg.so.8 -> libjpeg.so.8.0.2
libjpeg.so.8.0.2
libwebkitgtk-1.0.so -> libwebkitgtk-1.0.so.0.22.17
libwebkitgtk-1.0.so.0 -> libwebkitgtk-1.0.so.0.22.17
libwebkitgtk-1.0.so.0.22.17

Fixes #12

### CODE REVIEW

**Comment by liias** [comment]
Yay, first pull request. Thanks! Will review this or next week.

**Comment by snaggen** [comment]
Realized I forgot to clean it up, will do that tomorrow I think

File: src/main/java/io/github/liias/monkey/project/sdk/SdkHelper.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+import com.intellij.execution.configurations.RuntimeConfigurationException;
+import com.intellij.openapi.projectRoots.Sdk;
+import com.intellij.openapi.util.SystemInfoRt;
+import org.jetbrains.annotations.NotNull;
+
+public abstract class SdkHelper {
+	protected final Sdk sdk;
+
+	SdkHelper(Sdk sdk) {
+		this.sdk = sdk;
```
Comment (liias) [inline src/main/java/io/github/liias/monkey/project/sdk/SdkHelper.java]: As sdk is unused here I think this helper class could be simpler if having only static methods and no subclasses.

**Comment by snaggen** [comment]
So, I reworked the SdkHelper to remove the subclasses, and allow static access. As you said, it made things much cleaner. 
I squashed the cleanup commit, to avoid commit log pollution.

**Comment by liias** [comment]
Alright, thanks!
I tested compiling and running in simulator on Windows.

Created rel 0.3.8. JetBrains has manual approval process, so expect it in a day or two.
